"use strict";

const SECURITY = Object.freeze({ maxCommand: 1000, maxCode: 40000, maxPackage: 1024 * 1024, allowedThemes: ["windows", "ios", "resume"], allowedApps: ["about", "resume", "projects", "files", "browser", "terminal", "ide", "designer", "transpiler", "agent", "store", "settings", "calculator"] });
const APP_META = Object.freeze({
  about:{title:"About Rey",sub:"Profile & experience",icon:"RV",className:"profile-icon",w:920,h:650},resume:{title:"Resume.pdf",sub:"PDF Viewer",icon:"▤",className:"resume-icon",w:900,h:690},projects:{title:"Projects",sub:"Selected work",icon:"◇",className:"projects-icon",w:920,h:650},files:{title:"File Explorer",sub:"Portfolio (C:)",icon:"▰",className:"folder-icon",w:900,h:600},browser:{title:"Rey Browser",sub:"portfolio://home",icon:"◎",className:"browser-icon",w:930,h:640},terminal:{title:"Terminal",sub:"Local developer workspace",icon:"›_",className:"terminal-icon",w:960,h:610},ide:{title:"Rey IDE",sub:"portfolio-os",icon:"IJ",className:"ide-icon",w:980,h:660},designer:{title:"GUI Designer",sub:"Visual + code workspace",icon:"⌘",className:"designer-icon",w:1180,h:720},transpiler:{title:"Transpiler.exe",sub:"HumanCode compiler",icon:"{ }",className:"transpiler-icon",w:1040,h:650},agent:{title:"Rey Local AI",sub:"On-device model",icon:"✦",className:"agent-icon",w:850,h:620},store:{title:"App Studio",sub:"Local package manager",icon:"⊞",className:"store-icon",w:860,h:610},settings:{title:"Settings",sub:"System personalization",icon:"⚙",className:"settings-icon",w:820,h:640},calculator:{title:"Calculator",sub:"Standard",icon:"±",className:"calculator-icon",w:400,h:600}
});
const $=(selector,root=document)=>root.querySelector(selector);
const $$=(selector,root=document)=>[...root.querySelectorAll(selector)];
const clamp=(value,min,max)=>Math.min(max,Math.max(min,value));
const slug=value=>String(value||"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,42)||"profile";
const cleanText=(value,max=160)=>String(value??"").replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g,"").slice(0,max);
const cssEscape=value=>globalThis.CSS?.escape?CSS.escape(String(value)):String(value).replace(/[^A-Za-z0-9_-]/g,"\\$&");
const make=(tag,className,text)=>{const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node};
const storage={get(key,fallback){try{const raw=localStorage.getItem(key);if(!raw||raw.length>SECURITY.maxPackage)return fallback;return JSON.parse(raw)}catch{return fallback}},set(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true}catch{return false}}};
const defaultSettings=()=>({theme:"windows",accent:"#59a8ff",transparency:78,motion:true,profile:"Rey Victor Mendillo"});
let settings=defaultSettings();
let zTop=20,cascade=0,deferredInstall=null;
const openWindows=new Map();

function loadSettings(){
  const profiles=storage.get("portfolio-os:profiles",{active:"Rey Victor Mendillo",entries:{}});
  const active=cleanText(profiles.active||"Rey Victor Mendillo",40);
  const saved=profiles.entries&&profiles.entries[slug(active)];
  settings={...defaultSettings(),...(saved||{}),profile:active};
  if(!SECURITY.allowedThemes.includes(settings.theme))settings.theme="windows";
  if(!/^#[0-9a-f]{6}$/i.test(settings.accent))settings.accent="#59a8ff";
  settings.transparency=clamp(Number(settings.transparency)||78,55,96);
  settings.motion=settings.motion!==false;
  applySettings();
}
function saveSettings(){
  const profiles=storage.get("portfolio-os:profiles",{active:settings.profile,entries:{}});
  profiles.active=settings.profile;profiles.entries=profiles.entries&&typeof profiles.entries==="object"?profiles.entries:{};profiles.entries[slug(settings.profile)]={...settings};storage.set("portfolio-os:profiles",profiles);
}
function applySettings(){
  document.body.dataset.theme=settings.theme;document.body.dataset.motion=settings.motion?"on":"off";
  const rgb=[parseInt(settings.accent.slice(1,3),16),parseInt(settings.accent.slice(3,5),16),parseInt(settings.accent.slice(5,7),16)];
  document.documentElement.style.setProperty("--accent",settings.accent);document.documentElement.style.setProperty("--accent-rgb",rgb.join(","));document.documentElement.style.setProperty("--glass",String(settings.transparency/100));
  $$('[data-theme-choice]').forEach(button=>button.classList.toggle("active",button.dataset.themeChoice===settings.theme));
  $$('[data-settings-name]').forEach(node=>node.textContent=settings.profile);
}
function toast(title,message=""){
  const region=$("#toastRegion"),node=make("div","toast"),strong=make("b",null,cleanText(title,80)),span=make("span",null,cleanText(message,180));node.append(strong,span);region.append(node);setTimeout(()=>{node.classList.add("out");setTimeout(()=>node.remove(),280)},3600);
}
function updateClock(){
  const now=new Date(),time=now.toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}),date=now.toLocaleDateString([],{month:"2-digit",day:"2-digit",year:"numeric"});
  $("#clockTime").textContent=time;$("#clockDate").textContent=date;$("#lockTime").textContent=time;$("#lockDate").textContent=now.toLocaleDateString([],{weekday:"long",month:"long",day:"numeric"});
}
function closePanels(except=""){$$(".panel-pop.open").forEach(panel=>{if(panel.id!==except){panel.classList.remove("open");panel.setAttribute("aria-hidden","true")}});$("#contextMenu").classList.remove("open")}
function togglePanel(id){const panel=$("#"+id),opening=!panel.classList.contains("open");closePanels(id);panel.classList.toggle("open",opening);panel.setAttribute("aria-hidden",String(!opening));if(opening&&id==="startMenu")setTimeout(()=>$("#startSearch").focus(),80)}
function focusWindow(win){zTop+=1;win.style.zIndex=zTop;$$('.app-window.focused').forEach(item=>item.classList.remove("focused"));win.classList.add("focused");$$('.running-apps button').forEach(button=>button.classList.toggle("active",button.dataset.app===win.dataset.app))}
function createTaskButton(id,meta){const button=make("button");button.type="button";button.dataset.app=id;button.setAttribute("aria-label",meta.title);const icon=make("span","app-icon "+meta.className,meta.icon);button.append(icon);button.addEventListener("click",()=>{const win=openWindows.get(id);if(!win)return;if(win.classList.contains("minimized")){win.classList.remove("minimized");focusWindow(win)}else if(win.classList.contains("focused")){minimizeWindow(win)}else focusWindow(win)});$("#runningApps").append(button)}
function openApp(id,customPackage=null){
  closePanels();if(!SECURITY.allowedApps.includes(id)&&!id.startsWith("custom-"))return;
  const existing=openWindows.get(id);if(existing){existing.classList.remove("minimized");focusWindow(existing);return existing}
  const meta=customPackage?{title:cleanText(customPackage.name,60),sub:"Installed Portfolio app",icon:cleanText(customPackage.icon||"◆",3),className:"store-icon",w:720,h:520}:APP_META[id];if(!meta)return;
  const shell=$("#windowShell").content.firstElementChild.cloneNode(true);shell.dataset.app=id;shell.setAttribute("aria-label",meta.title);
  const icon=$(".window-title .app-icon",shell);icon.textContent=meta.icon;icon.classList.add(meta.className);$(".window-title strong",shell).textContent=meta.title;$(".window-title small",shell).textContent=meta.sub;
  const availableW=Math.max(320,innerWidth-24),availableH=Math.max(260,innerHeight-118);const w=Math.min(meta.w,availableW),h=Math.min(meta.h,availableH);cascade=(cascade+1)%7;shell.style.width=w+"px";shell.style.height=h+"px";shell.style.left=Math.max(4,(innerWidth-w)/2+cascade*16-40)+"px";shell.style.top=Math.max(4,(availableH-h)/2+cascade*13)+"px";
  if(customPackage)renderCustomApp($(".window-body",shell),customPackage);else{const template=$("#app-"+id);if(!template)return;$(".window-body",shell).append(template.content.cloneNode(true))}
  $("#windowLayer").append(shell);openWindows.set(id,shell);createTaskButton(id,meta);wireWindow(shell);focusWindow(shell);if(!customPackage)initApp(id,shell);return shell;
}
function closeWindow(win){win._dispose?.();win.classList.add("closing");setTimeout(()=>{const id=win.dataset.app;win.remove();openWindows.delete(id);$(`.running-apps button[data-app="${cssEscape(id)}"]`)?.remove()},250)}
function minimizeWindow(win){win.classList.add("minimized");win.classList.remove("focused")}
function maximizeWindow(win){win.classList.toggle("maximized");focusWindow(win)}
function wireWindow(win){
  const titlebar=$(".titlebar",win);titlebar.addEventListener("pointerdown",event=>{if(event.button!==0||event.target.closest("button")||win.classList.contains("maximized"))return;focusWindow(win);const startX=event.clientX,startY=event.clientY,left=innerWidth<=820?(parseFloat(win.style.getPropertyValue("--touch-x"))||4):(parseFloat(win.style.left)||0),top=innerWidth<=820?(parseFloat(win.style.getPropertyValue("--touch-y"))||3):(parseFloat(win.style.top)||0);titlebar.setPointerCapture(event.pointerId);const move=e=>{win.style.transition="none";if(innerWidth<=820){win.style.setProperty("--touch-x",clamp(left+e.clientX-startX,0,Math.max(0,innerWidth-160))+"px");win.style.setProperty("--touch-y",clamp(top+e.clientY-startY,0,$("#windowLayer").clientHeight-45)+"px");return}win.style.left=clamp(left+e.clientX-startX,0,Math.max(0,innerWidth-win.offsetWidth))+"px";win.style.top=clamp(top+e.clientY-startY,0,$("#windowLayer").clientHeight-42)+"px"};const up=()=>{titlebar.removeEventListener("pointermove",move);titlebar.removeEventListener("pointerup",up);titlebar.removeEventListener("pointercancel",up);win.style.transition=""};titlebar.addEventListener("pointermove",move);titlebar.addEventListener("pointerup",up);titlebar.addEventListener("pointercancel",up)});
  titlebar.addEventListener("dblclick",()=>maximizeWindow(win));win.addEventListener("pointerdown",()=>focusWindow(win));
  $$(".window-controls button",win).forEach(button=>button.addEventListener("click",()=>({close:closeWindow,minimize:minimizeWindow,maximize:maximizeWindow}[button.dataset.action])(win)));
  const handle=$(".resize-handle",win);handle.addEventListener("pointerdown",event=>{if(win.classList.contains("maximized"))return;event.stopPropagation();const x=event.clientX,y=event.clientY,w=win.offsetWidth,h=win.offsetHeight;handle.setPointerCapture(event.pointerId);const move=e=>{win.style.transition="none";win.style.width=clamp(w+e.clientX-x,320,innerWidth-(parseFloat(win.style.left)||0))+"px";win.style.height=clamp(h+e.clientY-y,260,$("#windowLayer").clientHeight-(parseFloat(win.style.top)||0))+"px"};const up=()=>{handle.removeEventListener("pointermove",move);handle.removeEventListener("pointerup",up);handle.removeEventListener("pointercancel",up);win.style.transition=""};handle.addEventListener("pointermove",move);handle.addEventListener("pointerup",up);handle.addEventListener("pointercancel",up)});
}

function tokenizeMath(expression){
  const source=String(expression).trim();if(source.length>160||!/^[\d\sA-Za-z_.+\-*/%()]+$/.test(source))throw new Error("Unsupported expression");const tokens=source.match(/\d+(?:\.\d+)?|[A-Za-z_]\w*|[()+\-*/%]/g)||[];if(tokens.join("").length!==source.replace(/\s/g,"").length)throw new Error("Invalid expression");return tokens;
}
function safeArithmetic(expression,variables={}) {
  const tokens=tokenizeMath(expression);let i=0;
  const factor=()=>{const t=tokens[i++];if(t==="-")return -factor();if(t==="+")return factor();if(t==="("){const v=sum();if(tokens[i++]!==")")throw new Error("Mismatched parentheses");return v}if(t===undefined)throw new Error("Incomplete expression");if(/^\d/.test(t))return Number(t);if(Object.prototype.hasOwnProperty.call(variables,t)){const n=Number(variables[t]);if(Number.isFinite(n))return n}throw new Error("Unknown value: "+t)};
  const product=()=>{let v=factor();while(["*","/","%"].includes(tokens[i])){const op=tokens[i++],rhs=factor();if(op!=="*"&&rhs===0)throw new Error("Division by zero");v=op==="*"?v*rhs:op==="/"?v/rhs:v%rhs}return v};
  const sum=()=>{let v=product();while(["+","-"].includes(tokens[i])){const op=tokens[i++],rhs=product();v=op==="+"?v+rhs:v-rhs}return v};
  const v=sum();if(i!==tokens.length||!Number.isFinite(v))throw new Error("Invalid expression");return Math.round(v*1e10)/1e10;
}
function evaluateValue(source,env={}){
  let value=String(source).trim();if((value.startsWith('"')&&value.endsWith('"'))||(value.startsWith("'")&&value.endsWith("'")))return value.slice(1,-1).replace(/\\n/g,"\n");if(/^f["']/.test(value)){const body=value.slice(2,-1);return body.replace(/\{([A-Za-z_]\w*)\}/g,(_,name)=>cleanText(env[name]??"",200))}if(Object.prototype.hasOwnProperty.call(env,value))return env[value];try{return safeArithmetic(value,env)}catch{return cleanText(value,300)}
}
function downloadText(name,text,type="text/plain"){const blob=new Blob([String(text)],{type}),url=URL.createObjectURL(blob),link=make("a");link.href=url;link.download=cleanText(name,80).replace(/[^A-Za-z0-9._-]/g,"-");document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}

function initApp(id,win){({files:initFiles,browser:initBrowser,terminal:initTerminal,ide:initIDE,designer:initDesigner,transpiler:initTranspiler,agent:initAgent,store:initStore,settings:win=>{initSettings(win);wireSettingsNavigation(win)},calculator:initCalculator}[id]||(()=>{}))(win)}

const FILE_ROUTES={
  home:[{name:"Resume.pdf",icon:"▤",type:"PDF document",open:"resume"},{name:"Projects",icon:"◇",type:"Folder",route:"projects"},{name:"Developer",icon:"{ }",type:"Folder",route:"developer"},{name:"About Rey",icon:"RV",type:"Portfolio profile",open:"about"}],
  documents:[{name:"Resume.pdf",icon:"▤",type:"PDF document",open:"resume"},{name:"career-notes.md",icon:"▧",type:"Markdown document",text:"# Rey Victor Mendillo\n\nSoftware Engineer at CHAMP Cargosystems.\n\nWork areas: enterprise software, Java, Spring, Angular, Python, AI and machine learning.\n\nOpen Resume.pdf for the full resume."},{name:"skills.json",icon:"{ }",type:"JSON file",text:JSON.stringify({languages:["Java","Python","TypeScript"],frameworks:["Spring","Angular"],areas:["AI/ML","NLP","Computer Vision","Oracle","OAuth"]},null,2)}],
  projects:[{name:"Skyler",icon:"◇",type:"ONE Record project",open:"projects"},{name:"Gesture Cursor",icon:"◇",type:"Computer vision",open:"projects"},{name:"Churn Prediction",icon:"◇",type:"Machine learning",open:"projects"},{name:"Summarizer",icon:"◇",type:"NLP project",open:"projects"}],
  developer:[{name:"Rey IDE",icon:"IJ",type:"Application",open:"ide"},{name:"Terminal",icon:">_",type:"Application",open:"terminal"},{name:"GUI Designer",icon:"⌘",type:"Application",open:"designer"},{name:"Transpiler.exe",icon:"{ }",type:"Portfolio application",open:"transpiler"}],
  thispc:[{name:"Portfolio (C:)",icon:"▱",type:"Local drive",route:"drive"},{name:"Installed Apps",icon:"⊞",type:"Local packages",open:"store"}],
  drive:[{name:"Users",icon:"▰",type:"Folder",route:"home"},{name:"Program Files",icon:"▰",type:"Folder",route:"developer"},{name:"Portfolio",icon:"▰",type:"Folder",route:"projects"}]
};
function initFiles(win){
  let current="home",history=["home"],index=0;const path=$("[data-file-path]",win),content=$("[data-files-content]",win),search=$("[data-file-search]",win),back=$("[data-file-back]",win),forward=$("[data-file-forward]",win);
  const activate=item=>{if(item.open)openApp(item.open);else if(item.route)go(item.route);else if(item.text!==undefined)go(current+"/"+item.name)};
  const render=()=>{
    content.replaceChildren();const [route,file]=current.split("/"),query=search.value.trim().toLowerCase();
    const document=(FILE_ROUTES[route]||[]).find(item=>item.name===file);
    if(document){const reader=make("section","file-document"),download=make("button",null,"Download "+document.name);download.type="button";download.onclick=()=>downloadText(document.name,document.text);reader.append(download,make("pre",null,document.text));content.append(reader)}
    else (FILE_ROUTES[route]||[]).filter(item=>item.name.toLowerCase().includes(query)).forEach(item=>{const button=make("button","file-item");button.type="button";button.append(make("span",null,item.icon),make("b",null,item.name),make("small",null,item.type));button.addEventListener("dblclick",()=>activate(item));button.addEventListener("click",()=>{if(innerWidth<=820)activate(item)});button.addEventListener("keydown",e=>{if(e.key==="Enter"&&innerWidth>820)activate(item)});content.append(button)});
    path.textContent=(route==="thispc"?"This PC":route.charAt(0).toUpperCase()+route.slice(1))+(file?" / "+file:"");back.disabled=index===0;forward.disabled=index===history.length-1;
    $$('[data-file-route]',win).forEach(button=>button.classList.toggle("active",button.dataset.fileRoute===route));
  };
  const go=route=>{if(!FILE_ROUTES[route.split("/")[0]])return;current=route;search.value="";history=history.slice(0,index+1);history.push(route);index++;render()};
  $$('[data-file-route]',win).forEach(button=>button.addEventListener("click",()=>go(button.dataset.fileRoute)));search.addEventListener("input",render);back.onclick=()=>{if(index>0){current=history[--index];render()}};forward.onclick=()=>{if(index<history.length-1){current=history[++index];render()}};render();
}
function initBrowser(win){
  const address=$("[data-browser-address]",win),page=$("[data-browser-page]",win);let history=["portfolio://home"],index=0;
  const addParagraph=(root,text)=>root.append(make("p",null,text));
  const render=raw=>{let value=cleanText(raw,300).trim()||"portfolio://home";if(/^[a-z0-9.-]+\.[a-z]{2,}(?:\/|$)/i.test(value))value="https://"+value;page.replaceChildren();if(/^https?:\/\//i.test(value)){let parsed;try{parsed=new URL(value)}catch{parsed=null}if(!parsed||!["http:","https:"].includes(parsed.protocol)){navigate("portfolio://home",false);return}const tools=make("div","browser-frame-tools"),link=make("a",null,"Open in browser");link.href=parsed.href;link.target="_blank";link.rel="noopener noreferrer";tools.append(make("span",null,"Some websites block embedding."),link);const frame=make("iframe","browser-embed");frame.title="Website: "+parsed.hostname;frame.sandbox="allow-scripts allow-forms allow-popups";frame.referrerPolicy="no-referrer";frame.src=parsed.href;page.append(tools,frame);page.style.padding="0";address.value=parsed.href;return}
    const route=value.toLowerCase().replace("portfolio://","").replace(/\/.*/,"")||"home",home=make("div","browser-home");home.append(make("div","browser-logo","RV"));const titles={home:"Rey on the web",about:"About Rey",projects:"Selected projects",terminal:"Developer workspace",resume:"Resume"};home.append(make("h1",null,titles[route]||titles.home));const copy={home:"A local, privacy-minded browser for navigating Rey Portfolio OS and launching trusted external profiles.",about:"Software Engineer at CHAMP Cargosystems, building enterprise and intelligent systems with Java, Spring, Angular, Python, and AI.",projects:"Explore Skyler, computer-vision interaction, churn prediction, and natural-language summarization.",terminal:"Open the local terminal, IDE, GUI Designer, or HumanCode Transpiler.",resume:"View Rey Victor Mendillo’s real PDF resume inside the Portfolio OS document viewer."};addParagraph(home,copy[route]||copy.home);const links=make("div","browser-links");[{label:"About",route:"portfolio://about",app:"about"},{label:"Projects",route:"portfolio://projects",app:"projects"},{label:"Developer",route:"portfolio://terminal",app:"terminal"},{label:"Resume PDF",route:"portfolio://resume",app:"resume"},{label:"LinkedIn",route:"https://ph.linkedin.com/in/rvmendillo"},{label:"GitHub",route:"https://github.com/rvmendillo"}].forEach(item=>{const button=make("button");button.type="button";button.append(make("b",null,item.label),make("p",null,item.route));button.addEventListener("click",()=>item.app?openApp(item.app):navigate(item.route));links.append(button)});home.append(links);page.append(home);address.value="portfolio://"+(titles[route]?route:"home")};
  const navigate=(value,push=true)=>{render(value);if(push){history=history.slice(0,index+1);history.push(address.value);index=history.length-1}};const go=()=>navigate(address.value);$("[data-browser-go]",win).addEventListener("click",go);address.addEventListener("keydown",e=>{if(e.key==="Enter")go()});$("[data-browser-refresh]",win).addEventListener("click",()=>render(history[index]));$("[data-browser-back]",win).addEventListener("click",()=>{if(index>0){index--;render(history[index])}});$("[data-browser-forward]",win).addEventListener("click",()=>{if(index<history.length-1){index++;render(history[index])}});render(history[0]);
}
function initTerminal(win){
  const output=$("[data-terminal-output]",win),form=$("[data-terminal-form]",win),input=$("[data-terminal-input]",win),language=$("[data-terminal-language]",win),code=$("[data-terminal-code]",win),codeOutput=$("[data-terminal-code-output]",win);
  const line=(text,className="")=>{const node=make("div",className,cleanText(text,4000));output.append(node);output.scrollTop=output.scrollHeight};line("Rey Portfolio OS [Version 10.0.2026]","success");line("Safe local terminal. Type 'help' for commands.\n");
  const command=raw=>{const value=cleanText(raw,SECURITY.maxCommand).trim();if(!value)return;line("PS C:\\Users\\Rey> "+value,"command");const [name,...parts]=value.split(/\s+/),args=parts.join(" ");switch(name.toLowerCase()){
    case"help":line("help · whoami · about · skills · projects · dir · date · clear · calc <expression> · theme <windows|ios|resume> · open <app> · python · java · cpp · security · neofetch");break;
    case"whoami":line("Rey Victor Mendillo — Software Engineer / AI builder");break;case"about":line("Enterprise software, AI/ML, thoughtful interfaces, mathematics, and creative systems.");break;case"skills":line("Java · Spring · Angular · TypeScript · Python · AI/ML · NLP · Computer Vision · Oracle · OAuth");break;case"projects":line("Skyler · Gesture Cursor · Rotational Churn Prediction · Text Summarization");break;case"dir":line("About Rey\nResume.pdf\nProjects/\nDeveloper/\nTranspiler.exe\nGUI Designer.posapp");break;case"date":line(new Date().toString());break;case"clear":output.replaceChildren();break;case"calc":try{line(String(safeArithmetic(args)),"success")}catch(error){line(error.message,"error")}break;
    case"theme":if(SECURITY.allowedThemes.includes(args)){settings.theme=args;saveSettings();applySettings();line("Theme changed to "+args,"success")}else line("Choose windows, ios, or resume.","error");break;
    case"open":{const app=args.toLowerCase().replace(/[^a-z]/g,"");const aliases={gui:"designer",gdesigner:"designer",ai:"agent",transpilerexe:"transpiler",pdf:"resume"};const target=aliases[app]||app;if(SECURITY.allowedApps.includes(target)){openApp(target);line("Opening "+target+"…","success")}else line("App not found.","error");break}
    case"python":language.value="Python";line("Code runner switched to Python.","success");break;case"java":language.value="Java";line("Code runner switched to Java.","success");break;case"cpp":language.value="C++";line("Code runner switched to C++.","success");break;case"security":line("CSP active · local settings · package validation · bounded execution · review code before running","success");break;case"neofetch":line("        ▣  Rey Portfolio OS\n       ▣▣  Theme: "+settings.theme+"\n      ▣▣▣  Runtime: Browser / PWA\n     ▣▣▣▣  Profile: "+settings.profile+"\n    ▣▣▣▣▣  Local AI: Open Local AI to load the model","success");break;default:if(name.toLowerCase()==="echo")line(args);else line(`'${name}' is not recognized. Type 'help'.`,"error")}
  };
  form.addEventListener("submit",event=>{event.preventDefault();command(input.value);input.value=""});$("[data-terminal-run]",win).addEventListener("click",async event=>{const button=event.currentTarget;button.disabled=true;codeOutput.textContent="Starting runtime…";try{const result=await window.ReyDev.runCode(code.value,language.value);codeOutput.textContent=result.output+"\nExit code: "+result.exitCode}catch(error){codeOutput.textContent="Error: "+error.message}finally{button.disabled=false}});
}
const IDE_FILES={
  "main.py":`name = "Rey"\nskills = ["Java", "Python", "Angular", "AI"]\n\ndef introduce(person):\n    return f"Hello, {person}. Welcome to Portfolio OS."\n\nprint("Hello from Portfolio OS")\nprint(6 * 7)`,
  "agent.py":`class LocalAgent:\n    def __init__(self, knowledge):\n        self.knowledge = knowledge\n\n    def answer(self, question):\n        return "Sample response: " + question\n\nprint("Python class example — use the AI panel for model inference.")`,
  "gui.yml":`app: Calculator\ncomponents:\n  - id: input1\n    type: input\n  - id: calculate\n    type: button\n    operation: add\n  - id: result\n    type: output\nconnections:\n  - input1 -> calculate\n  - calculate -> result`
};
function initIDE(win) {
  const profile = settings.profile;
  window.ReyDev.mountIDE(win, {
    profile, samples: IDE_FILES,
    previewYAML(source) { const project = parseProjectYAML(source); if (!project.components.length) throw new Error("No GUI components found."); openCustomAppWindow(project, "custom-ide-preview"); },
    notify: toast
  }).then(dispose => { if(win.classList.contains("closing")||!win.isConnected)dispose();else win._dispose=dispose; }).catch(error => {
    win.querySelector(".window-body").textContent = "IDE could not start: " + error.message;
  });
}

const COMPONENT_DEFAULTS={label:{text:"Label",w:130},input:{text:"Input",w:170},button:{text:"Calculate",w:120},output:{text:"Result",w:170}};
function newDesignerProject(){return{name:"Untitled",components:[],connections:[],selected:null,format:"yaml",connectMode:false,connectStart:null}}
function normalizeComponent(raw,index){const type=["label","input","button","output"].includes(raw.type)?raw.type:"label",base=COMPONENT_DEFAULTS[type];return{id:slug(raw.id||type+(index+1)).replace(/-/g,"_").slice(0,24),type,text:cleanText(raw.text||base.text,80),x:clamp(Number.isFinite(Number(raw.x))?Number(raw.x):40,0,680),y:clamp(Number.isFinite(Number(raw.y))?Number(raw.y):40,0,400),w:clamp(Number(raw.w)||base.w,60,500),operation:["none","add","subtract","multiply","divide","formula","join","upper","lower","clear"].includes(raw.operation)?raw.operation:"none",formula:cleanText(raw.formula||"",120)}}
function validateProject(raw){const source=raw&&typeof raw==="object"?raw:{};const components=Array.isArray(source.components)?source.components.slice(0,50).map(normalizeComponent):[],ids=new Set(),unique=[];components.forEach((item,index)=>{let id=item.id||"component"+(index+1);while(ids.has(id))id=id+"_"+(index+1);item.id=id;ids.add(id);unique.push(item)});const connections=Array.isArray(source.connections)?source.connections.slice(0,100).map(c=>({from:cleanText(c.from,24),to:cleanText(c.to,24)})).filter(c=>ids.has(c.from)&&ids.has(c.to)&&c.from!==c.to):[];return{name:cleanText(source.name||"Untitled",48),components:unique,connections,selected:null,format:"yaml",connectMode:false,connectStart:null}}
function yamlQuote(value){return JSON.stringify(cleanText(value,160))}
function projectToYAML(project){const lines=[`app: ${yamlQuote(project.name)}`,"components:"];project.components.forEach(c=>{lines.push(`  - id: ${c.id}`,`    type: ${c.type}`,`    text: ${yamlQuote(c.text)}`,`    x: ${Math.round(c.x)}`,`    y: ${Math.round(c.y)}`,`    width: ${Math.round(c.w)}`);if(c.type==="button"){lines.push(`    operation: ${c.operation}`);if(c.formula)lines.push(`    formula: ${yamlQuote(c.formula)}`)}});lines.push("connections:");project.connections.forEach(c=>lines.push(`  - from: ${c.from}`,`    to: ${c.to}`));return lines.join("\n")}
function projectToPythonUI(project){const lines=["from portfolio_os import App",`ui = App(${JSON.stringify(project.name)}, width=760, height=450)`,""];project.components.forEach(c=>{const method=c.type;lines.push(`ui.${method}(${JSON.stringify(c.id)}, text=${JSON.stringify(c.text)}, x=${Math.round(c.x)}, y=${Math.round(c.y)}, width=${Math.round(c.w)}${c.type==="button"?`, operation=${JSON.stringify(c.operation)}, formula=${JSON.stringify(c.formula)}`:""})`)});lines.push("");project.connections.forEach(c=>lines.push(`ui.connect(${JSON.stringify(c.from)}, ${JSON.stringify(c.to)})`));lines.push("ui.run()");return lines.join("\n")}
function actionMap(project,button){const incoming=project.connections.filter(c=>c.to===button.id).map(c=>c.from),outgoing=project.connections.filter(c=>c.from===button.id).map(c=>c.to);return{incoming,outgoing}}
function pythonExpression(button,inputs,widgetSuffix=".get()"){
  const refs=inputs.length?inputs:["input1"];const vals=refs.map(id=>`${id}${widgetSuffix}`);if(button.operation==="join")return vals.join(' + " " + ');if(button.operation==="upper")return `${vals[0]}.upper()`;if(button.operation==="lower")return `${vals[0]}.lower()`;if(button.operation==="formula"&&button.formula){let formula=button.formula;refs.forEach((id,i)=>{formula=formula.replace(new RegExp(`\\b${id}\\b|\\binput${i+1}\\b`,"g"),`float(${id}${widgetSuffix})`)});return formula}const op={add:" + ",subtract:" - ",multiply:" * ",divide:" / "}[button.operation]||" + ";return vals.map(v=>`float(${v})`).join(op)}
function projectToTkinter(project){const lines=["import tkinter as tk","from tkinter import ttk","","root = tk.Tk()",`root.title(${JSON.stringify(project.name)})`,`root.geometry("760x450")`,""];project.components.forEach(c=>{if(c.type==="input")lines.push(`${c.id} = ttk.Entry(root)`,`${c.id}.place(x=${Math.round(c.x)}, y=${Math.round(c.y)}, width=${Math.round(c.w)})`);else if(c.type==="output")lines.push(`${c.id}_var = tk.StringVar(value=${JSON.stringify(c.text)})`,`${c.id} = ttk.Label(root, textvariable=${c.id}_var)`,`${c.id}.place(x=${Math.round(c.x)}, y=${Math.round(c.y)}, width=${Math.round(c.w)})`);else if(c.type==="label")lines.push(`${c.id} = ttk.Label(root, text=${JSON.stringify(c.text)})`,`${c.id}.place(x=${Math.round(c.x)}, y=${Math.round(c.y)}, width=${Math.round(c.w)})`)});project.components.filter(c=>c.type==="button").forEach(button=>{const map=actionMap(project,button),target=map.outgoing[0]||project.components.find(c=>c.type==="output")?.id||"result";lines.push("",`def on_${button.id}():`);if(button.operation==="clear"){map.incoming.forEach(id=>lines.push(`    ${id}.delete(0, tk.END)`));lines.push(`    ${target}_var.set("")`)}else lines.push("    try:",`        value = ${pythonExpression(button,map.incoming)}`,`        ${target}_var.set(str(value))`,`    except (ValueError, ZeroDivisionError) as error:`,`        ${target}_var.set(f"Error: {error}")`);lines.push(`${button.id} = ttk.Button(root, text=${JSON.stringify(button.text)}, command=on_${button.id})`,`${button.id}.place(x=${Math.round(button.x)}, y=${Math.round(button.y)}, width=${Math.round(button.w)})`)});lines.push("","root.mainloop()");return lines.join("\n")}
function projectToPyQt(project){const lines=["import sys","from PyQt6.QtWidgets import QApplication, QWidget, QLabel, QLineEdit, QPushButton","","app = QApplication(sys.argv)","window = QWidget()",`window.setWindowTitle(${JSON.stringify(project.name)})`,`window.setGeometry(100, 100, 760, 450)`,""];project.components.forEach(c=>{const klass={label:"QLabel",input:"QLineEdit",button:"QPushButton",output:"QLabel"}[c.type];lines.push(`${c.id} = ${klass}(${JSON.stringify(c.text)}, window)`,`${c.id}.setGeometry(${Math.round(c.x)}, ${Math.round(c.y)}, ${Math.round(c.w)}, 34)`)});project.components.filter(c=>c.type==="button").forEach(button=>{const map=actionMap(project,button),target=map.outgoing[0]||"result";lines.push("",`def on_${button.id}():`,`    try:`,`        value = ${pythonExpression(button,map.incoming,".text()")}`,`        ${target}.setText(str(value))`,`    except (ValueError, ZeroDivisionError) as error:`,`        ${target}.setText(f"Error: {error}")`,`${button.id}.clicked.connect(on_${button.id})`)});lines.push("","window.show()","sys.exit(app.exec())");return lines.join("\n")}
function projectToKivy(project){const kv=["from kivy.app import App","from kivy.uix.floatlayout import FloatLayout","from kivy.uix.label import Label","from kivy.uix.textinput import TextInput","from kivy.uix.button import Button","","class GeneratedApp(App):","    def build(self):","        root = FloatLayout()"];project.components.forEach(c=>{const klass={label:"Label",input:"TextInput",button:"Button",output:"Label"}[c.type];kv.push(`        self.${c.id} = ${klass}(text=${JSON.stringify(c.text)}, size_hint=(None, None), size=(${Math.round(c.w)}, 40), pos=(${Math.round(c.x)}, ${Math.round(410-c.y)}))`,`        root.add_widget(self.${c.id})`)});project.components.filter(c=>c.type==="button").forEach(button=>kv.push(`        self.${button.id}.bind(on_press=self.on_${button.id})`));kv.push("        return root");project.components.filter(c=>c.type==="button").forEach(button=>{const map=actionMap(project,button),target=map.outgoing[0]||"result";kv.push("",`    def on_${button.id}(self, _button):`,`        try:`,`            value = ${pythonExpression(button,map.incoming.map(id=>"self."+id),".text")}`,`            self.${target}.text = str(value)`,`        except (ValueError, ZeroDivisionError) as error:`,`            self.${target}.text = f"Error: {error}"`)});kv.push("","GeneratedApp().run()");return kv.join("\n")}
function javaExpression(button,inputs){const vals=(inputs.length?inputs:["input1"]).map(id=>`${id}.getText()`);if(button.operation==="join")return `String.join(" ", ${vals.join(", ")})`;if(button.operation==="upper")return `${vals[0]}.toUpperCase()`;if(button.operation==="lower")return `${vals[0]}.toLowerCase()`;const op={add:" + ",subtract:" - ",multiply:" * ",divide:" / "}[button.operation]||" + ";return vals.map(v=>`Double.parseDouble(${v})`).join(op)}
function projectToSwing(project){const lines=["import javax.swing.*;","","public class GeneratedApp {","  public static void main(String[] args) {","    SwingUtilities.invokeLater(() -> {","      JFrame frame = new JFrame("+JSON.stringify(project.name)+");","      frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);","      frame.setSize(760, 450);","      frame.setLayout(null);"];project.components.forEach(c=>{const klass={label:"JLabel",input:"JTextField",button:"JButton",output:"JLabel"}[c.type];lines.push(`      ${klass} ${c.id} = new ${klass}(${JSON.stringify(c.text)});`,`      ${c.id}.setBounds(${Math.round(c.x)}, ${Math.round(c.y)}, ${Math.round(c.w)}, 34);`,`      frame.add(${c.id});`)});project.components.filter(c=>c.type==="button").forEach(button=>{const map=actionMap(project,button),target=map.outgoing[0]||"result";lines.push(`      ${button.id}.addActionListener(event -> {`,`        try {`,`          Object value = ${javaExpression(button,map.incoming)};`,`          ${target}.setText(String.valueOf(value));`,`        } catch (RuntimeException error) { ${target}.setText("Error: " + error.getMessage()); }`,`      });`)});lines.push("      frame.setVisible(true);","    });","  }","}");return lines.join("\n")}
function projectToWin32(project){const lines=["#include <windows.h>","#include <string>","","LRESULT CALLBACK WindowProc(HWND hwnd, UINT msg, WPARAM wParam, LPARAM lParam) {","  static HWND controls[128];","  switch (msg) {","    case WM_CREATE:"];project.components.forEach((c,index)=>{const klass=c.type==="button"?"BUTTON":c.type==="input"?"EDIT":"STATIC",style=c.type==="input"?"WS_CHILD | WS_VISIBLE | WS_BORDER | ES_AUTOHSCROLL":"WS_CHILD | WS_VISIBLE";lines.push(`      controls[${index}] = CreateWindowA("${klass}", ${JSON.stringify(c.text)}, ${style}, ${Math.round(c.x)}, ${Math.round(c.y)}, ${Math.round(c.w)}, 34, hwnd, (HMENU)${1000+index}, nullptr, nullptr);`)});lines.push("      return 0;","    case WM_COMMAND:");project.components.filter(c=>c.type==="button").forEach(button=>{const index=project.components.indexOf(button);lines.push(`      if (LOWORD(wParam) == ${1000+index}) {`,`        // Native handler for ${button.operation}; read connected EDIT controls, calculate, then SetWindowText.`,`        MessageBeep(MB_OK);`,`      }`)});lines.push("      return 0;","    case WM_DESTROY: PostQuitMessage(0); return 0;","  }","  return DefWindowProc(hwnd, msg, wParam, lParam);","}","","int WINAPI WinMain(HINSTANCE instance, HINSTANCE, LPSTR, int show) {","  WNDCLASSA wc{}; wc.lpfnWndProc = WindowProc; wc.hInstance = instance; wc.lpszClassName = \"PortfolioGeneratedApp\"; RegisterClassA(&wc);",`  HWND hwnd = CreateWindowExA(0, wc.lpszClassName, ${JSON.stringify(project.name)}, WS_OVERLAPPEDWINDOW, CW_USEDEFAULT, CW_USEDEFAULT, 760, 450, nullptr, nullptr, instance, nullptr);`,"  ShowWindow(hwnd, show); MSG msg{}; while (GetMessage(&msg, nullptr, 0, 0)) { TranslateMessage(&msg); DispatchMessage(&msg); } return 0;","}");return lines.join("\n")}
function generateProjectCode(project,format){return({yaml:projectToYAML,python:projectToPythonUI,tkinter:projectToTkinter,pyqt:projectToPyQt,kivy:projectToKivy,swing:projectToSwing,win32:projectToWin32}[format]||projectToYAML)(project)}
function parseScalar(value){const raw=value.trim();if(/^".*"$/.test(raw)){try{return JSON.parse(raw)}catch{return raw.slice(1,-1)}}return raw}
function parseProjectYAML(source){const project={name:"Imported App",components:[],connections:[]};let section="",current=null;for(const raw of String(source).split(/\r?\n/).slice(0,1000)){const line=raw.trim();if(!line||line.startsWith("#"))continue;if(line.startsWith("app:")){project.name=parseScalar(line.slice(4));continue}if(line==="components:"){section="components";continue}if(line==="connections:"){section="connections";current=null;continue}if(section==="components"&&line.startsWith("- id:")){current={id:parseScalar(line.slice(5))};project.components.push(current);continue}if(section==="components"&&current&&line.includes(":")){const at=line.indexOf(":"),key=line.slice(0,at).trim(),value=parseScalar(line.slice(at+1));current[key==="width"?"w":key]=["x","y","width","w"].includes(key)?Number(value):value;continue}if(section==="connections"&&line.startsWith("- from:")){current={from:parseScalar(line.slice(7)),to:""};project.connections.push(current);continue}if(section==="connections"&&current&&line.startsWith("to:")){current.to=parseScalar(line.slice(3));continue}const arrow=line.match(/^-\s*([A-Za-z_]\w*)\s*->\s*([A-Za-z_]\w*)/);if(section==="connections"&&arrow)project.connections.push({from:arrow[1],to:arrow[2]})}return validateProject(project)}
function parseProjectPython(source){const project={name:"Python UI",components:[],connections:[]};const app=String(source).match(/App\((['"])(.*?)\1/);if(app)project.name=app[2];for(const line of String(source).split(/\r?\n/).slice(0,1000)){let match=line.match(/ui\.(label|input|button|output)\((['"])([A-Za-z_]\w*)\2,(.*)\)/);if(match){const args=match[4],get=(name,fallback="")=>{const value=args.match(new RegExp(`${name}=["']([^"']*)["']`));return value?value[1]:fallback},num=(name,fallback)=>Number(args.match(new RegExp(`${name}=(\\d+)`))?.[1]||fallback);project.components.push({type:match[1],id:match[3],text:get("text",COMPONENT_DEFAULTS[match[1]].text),x:num("x",40),y:num("y",40),w:num("width",COMPONENT_DEFAULTS[match[1]].w),operation:get("operation","none"),formula:get("formula","")});continue}match=line.match(/ui\.connect\((['"])([A-Za-z_]\w*)\1,\s*(['"])([A-Za-z_]\w*)\3\)/);if(match)project.connections.push({from:match[2],to:match[4]})}return validateProject(project)}

function initDesigner(win){
  const stage=$("[data-designer-stage]",win),wires=$("[data-designer-wires]",win),inspector=$("[data-inspector-form]",win),empty=$("[data-inspector-empty]",win),code=$("[data-designer-code]",win),connections=$("[data-connection-list]",win),connectButton=$("[data-connect-mode]",win);let project=validateProject(storage.get("portfolio-os:designer:"+slug(settings.profile),newDesignerProject()));
  const selected=()=>project.components.find(c=>c.id===project.selected);
  const save=()=>storage.set("portfolio-os:designer:"+slug(settings.profile),{name:project.name,components:project.components,connections:project.connections});
  const updateCode=()=>{code.value=generateProjectCode(project,project.format)};
  const renderWires=()=>{wires.replaceChildren();project.connections.forEach(connection=>{const a=project.components.find(c=>c.id===connection.from),b=project.components.find(c=>c.id===connection.to);if(!a||!b)return;const x1=a.x+a.w,y1=a.y+17,x2=b.x,y2=b.y+17,path=document.createElementNS("http://www.w3.org/2000/svg","path");path.setAttribute("d",`M ${x1} ${y1} C ${x1+50} ${y1}, ${x2-50} ${y2}, ${x2} ${y2}`);wires.append(path)})};
  const renderConnections=()=>{connections.replaceChildren();if(!project.connections.length){connections.append(make("small",null,"No connections yet."));return}project.connections.forEach((connection,index)=>{const button=make("button",null,`${connection.from} → ${connection.to}  ×`);button.type="button";button.addEventListener("click",()=>{project.connections.splice(index,1);render();save()});connections.append(button)})};
  const fillInspector=()=>{const item=selected();empty.hidden=Boolean(item);inspector.hidden=!item;if(!item)return;["id","text","x","y","w","operation","formula"].forEach(name=>{const field=inspector.elements[name];if(field)field.value=item[name]??""})};
  const chooseConnection=id=>{if(!project.connectStart){project.connectStart=id;render();toast("Connection started","Choose the destination component.");return}if(project.connectStart!==id&&!project.connections.some(c=>c.from===project.connectStart&&c.to===id))project.connections.push({from:project.connectStart,to:id});project.connectStart=null;render();save()};
  const wireElement=(node,item)=>{node.addEventListener("pointerdown",event=>{event.preventDefault();event.stopPropagation();if(project.connectMode){chooseConnection(item.id);return}project.selected=item.id;fillInspector();$$('.designer-element',stage).forEach(el=>el.classList.toggle("selected",el.dataset.id===item.id));const rect=stage.getBoundingClientRect(),startX=event.clientX,startY=event.clientY,startLeft=item.x,startTop=item.y;node.setPointerCapture(event.pointerId);const move=e=>{item.x=clamp(Math.round(startLeft+e.clientX-startX),0,stage.clientWidth-item.w);item.y=clamp(Math.round(startTop+e.clientY-startY),0,stage.clientHeight-34);node.style.left=item.x+"px";node.style.top=item.y+"px";renderWires();fillInspector()};const up=()=>{node.removeEventListener("pointermove",move);node.removeEventListener("pointerup",up);updateCode();save()};node.addEventListener("pointermove",move);node.addEventListener("pointerup",up)});node.addEventListener("keydown",event=>{if(event.key==="Delete"){project.components=project.components.filter(c=>c.id!==item.id);project.connections=project.connections.filter(c=>c.from!==item.id&&c.to!==item.id);project.selected=null;render();save()}})};
  const render=()=>{stage.querySelectorAll(".designer-element").forEach(node=>node.remove());project.components.forEach(item=>{const node=make("button","designer-element",item.type==="input"?item.text+"…":item.text);node.type="button";node.dataset.id=item.id;node.dataset.type=item.type;node.style.left=item.x+"px";node.style.top=item.y+"px";node.style.width=item.w+"px";node.title=item.id;node.classList.toggle("selected",project.selected===item.id);node.classList.toggle("connecting",project.connectStart===item.id);wireElement(node,item);stage.append(node)});$(".stage-empty",stage).classList.toggle("hidden",project.components.length>0);connectButton.classList.toggle("active",project.connectMode);renderWires();renderConnections();fillInspector();updateCode()};
  const add=type=>{const count=project.components.filter(c=>c.type===type).length+1,item=normalizeComponent({type,id:type+count,text:COMPONENT_DEFAULTS[type].text,x:45+(count-1)*25,y:45+(project.components.length%6)*52},project.components.length);project.components.push(item);project.selected=item.id;render();save()};
  $$('[data-component]',win).forEach(button=>{button.addEventListener("click",()=>add(button.dataset.component));button.addEventListener("dragstart",event=>event.dataTransfer.setData("text/plain",button.dataset.component))});stage.addEventListener("dragover",event=>event.preventDefault());stage.addEventListener("drop",event=>{event.preventDefault();const type=event.dataTransfer.getData("text/plain");if(!COMPONENT_DEFAULTS[type])return;add(type);const item=selected(),rect=stage.getBoundingClientRect();item.x=clamp(Math.round(event.clientX-rect.left),0,stage.clientWidth-item.w);item.y=clamp(Math.round(event.clientY-rect.top),0,stage.clientHeight-34);render();save()});stage.addEventListener("pointerdown",event=>{if(event.target===stage||event.target.classList.contains("stage-grid")){project.selected=null;fillInspector();$$('.designer-element',stage).forEach(el=>el.classList.remove("selected"))}});
  inspector.addEventListener("input",event=>{const item=selected();if(!item)return;const field=event.target.name;if(!field)return;if(["x","y","w"].includes(field))item[field]=Number(event.target.value)||0;else if(field==="id"){const old=item.id,next=slug(event.target.value).replace(/-/g,"_").slice(0,24)||old;if(!project.components.some(c=>c!==item&&c.id===next)){item.id=next;project.selected=next;project.connections.forEach(c=>{if(c.from===old)c.from=next;if(c.to===old)c.to=next})}}else item[field]=cleanText(event.target.value,field==="formula"?120:80);render();save()});
  $("[data-designer-delete]",win).addEventListener("click",()=>{const item=selected();if(!item)return;project.components=project.components.filter(c=>c!==item);project.connections=project.connections.filter(c=>c.from!==item.id&&c.to!==item.id);project.selected=null;render();save()});connectButton.addEventListener("click",()=>{project.connectMode=!project.connectMode;project.connectStart=null;render()});
  $("[data-designer-new]",win).addEventListener("click",()=>{project=newDesignerProject();render();save()});$("[data-designer-demo]",win).addEventListener("click",()=>{project=validateProject({name:"Connected Calculator",components:[{id:"input1",type:"input",text:"First number",x:65,y:80,w:180},{id:"input2",type:"input",text:"Second number",x:65,y:140,w:180},{id:"calculate",type:"button",text:"Add values",x:310,y:108,w:135,operation:"add"},{id:"result",type:"output",text:"Result",x:510,y:108,w:180}],connections:[{from:"input1",to:"calculate"},{from:"input2",to:"calculate"},{from:"calculate",to:"result"}]});render();save()});
  $$('[data-format]',win).forEach(button=>button.addEventListener("click",()=>{project.format=button.dataset.format;$$('[data-format]',win).forEach(item=>item.classList.toggle("active",item===button));updateCode()}));$("[data-code-apply]",win).addEventListener("click",()=>{try{if(project.format==="yaml")project=parseProjectYAML(code.value);else if(project.format==="python")project=parseProjectPython(code.value);else throw new Error("Apply code supports YAML and Python UI formats.");render();save();toast("Code applied","The canvas and connections were regenerated.")}catch(error){toast("Could not apply code",error.message)}});$("[data-code-download]",win).addEventListener("click",()=>downloadText(project.name+({yaml:".yml",python:".py",tkinter:"-tkinter.py",pyqt:"-pyqt.py",kivy:"-kivy.py",swing:".java",win32:".cpp"}[project.format]||".txt"),code.value));
  $("[data-designer-run]",win).addEventListener("click",()=>openCustomAppWindow({...project,name:project.name+" Preview"},"custom-preview-"+Date.now()));$("[data-designer-package]",win).addEventListener("click",()=>{try{const pkg={format:"portfolio-os-app/v1",name:project.name,icon:"◆",components:project.components,connections:project.connections,createdAt:new Date().toISOString()};installPackage(pkg);downloadText(slug(project.name)+".posapp",JSON.stringify(pkg,null,2),"application/json");toast("App packaged","Installed locally and downloaded as .posapp")}catch(error){toast("Package not created",cleanText(error.message,160))}});render();
}
function executeCustomAction(packageData,buttonId,root){const button=packageData.components.find(c=>c.id===buttonId),incoming=packageData.connections.filter(c=>c.to===buttonId).map(c=>c.from),outgoing=packageData.connections.filter(c=>c.from===buttonId).map(c=>c.to),values={},ordered=[];incoming.forEach((id,index)=>{const field=$(`[data-custom-id="${cssEscape(id)}"]`,root),value=field?.value??field?.textContent??"";values[id]=value;values["input"+(index+1)]=value;ordered.push(value)});let result="";try{switch(button.operation){case"add":result=ordered.reduce((a,b)=>a+Number(b),0);break;case"subtract":result=ordered.slice(1).reduce((a,b)=>a-Number(b),Number(ordered[0]||0));break;case"multiply":result=ordered.reduce((a,b)=>a*Number(b),1);break;case"divide":result=ordered.slice(1).reduce((a,b)=>{if(Number(b)===0)throw new Error("Division by zero");return a/Number(b)},Number(ordered[0]||0));break;case"formula":result=safeArithmetic(button.formula,values);break;case"join":result=ordered.join(" ");break;case"upper":result=String(ordered[0]||"").toUpperCase();break;case"lower":result=String(ordered[0]||"").toLowerCase();break;case"clear":incoming.forEach(id=>{const node=$(`[data-custom-id="${cssEscape(id)}"]`,root);if(node&&"value"in node)node.value=""});result="";break;default:result=ordered.join(" ")}}catch(error){result="Error: "+cleanText(error.message,120)}outgoing.forEach(id=>{const node=$(`[data-custom-id="${cssEscape(id)}"]`,root);if(node)node.textContent=String(result)})}
function renderCustomApp(root,raw){const packageData=validateProject(raw),surface=make("div","custom-app-surface");surface.style.cssText="position:relative;width:760px;height:450px;max-width:100%;margin:18px auto;background:#eef3f8;color:#172033;border-radius:12px;overflow:auto";packageData.components.forEach(c=>{let node;if(c.type==="input"){node=make("input");node.type="text";node.placeholder=c.text;node.maxLength=200}else if(c.type==="button"){node=make("button",null,c.text);node.type="button";node.addEventListener("click",()=>executeCustomAction(packageData,c.id,surface))}else node=make(c.type==="output"?"output":"div",null,c.text);node.dataset.customId=c.id;node.style.cssText=`position:absolute;left:${c.x}px;top:${c.y}px;width:${c.w}px;min-height:36px;padding:8px;border:1px solid #b7c4d3;border-radius:6px;background:${c.type==="label"?"transparent":"#fff"};color:#172033`;surface.append(node)});root.style.overflow="auto";root.append(surface)}
function openCustomAppWindow(packageData,id="custom-"+slug(packageData.name)){return openApp(id,packageData)}

const HUMAN_KEYWORDS={
  "human-en":{say:["say","show","display","print"],set:["set"],ask:["ask"],if:["if"],elif:["else if"],else:["otherwise","else"],repeat:["repeat"],each:["for each"],fn:["function"],ret:["return"],end:["end"],class:["class"],true:["true"],false:["false"],and:["and"],or:["or"],not:["not"]},
  "human-fil":{say:["ipakita","ilabas","print"],set:["itakda","ilagay"],ask:["itanong","hingin"],if:["kung"],elif:["kundi kung"],else:["kundi"],repeat:["ulitin"],each:["para sa bawat"],fn:["gawain","tungkulin"],ret:["ibalik"],end:["wakas","tapusin"],class:["klase"],true:["totoo"],false:["mali"],and:["at"],or:["o"],not:["hindi"]}
};
function startsKeyword(line,words){return words.find(word=>line.toLowerCase()===word||line.toLowerCase().startsWith(word+" "))}
function normalizeHumanExpression(value,map){let text=value.trim().replace(/\bthen\b$|\bkaya\b$/i,"");[[map.true,"True"],[map.false,"False"],[map.and,"and"],[map.or,"or"],[map.not,"not"]].forEach(([words,replacement])=>words.forEach(word=>{text=text.replace(new RegExp(`\\b${word.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}\\b`,"gi"),replacement)}));return text}
function humanToPython(source,mode,customPrint=""){
  const map=HUMAN_KEYWORDS[mode]||HUMAN_KEYWORDS["human-en"],custom=cleanText(customPrint,24).toLowerCase();if(custom&&!map.say.includes(custom))map.say=[custom,...map.say];let indent=0;const output=["# Compiled locally by Rey Portfolio OS","# HumanCode → Python",""];
  for(const raw of String(source).split(/\r?\n/).slice(0,800)){const original=raw.trim();if(!original){output.push("");continue}if(original.startsWith("#")){output.push("    ".repeat(indent)+original);continue}const endWord=startsKeyword(original,map.end);if(endWord){indent=Math.max(0,indent-1);continue}let keyword,body,line="",opens=false;
    if((keyword=startsKeyword(original,map.elif))){indent=Math.max(0,indent-1);body=original.slice(keyword.length);line=`elif ${normalizeHumanExpression(body,map)}:`;opens=true}
    else if((keyword=startsKeyword(original,map.else))){indent=Math.max(0,indent-1);line="else:";opens=true}
    else if((keyword=startsKeyword(original,map.say))){body=original.slice(keyword.length).trim();line=`print(${body||JSON.stringify("")})`}
    else if((keyword=startsKeyword(original,map.set))){body=original.slice(keyword.length).trim();const match=body.match(/^([A-Za-z_]\w*)\s+(?:to|bilang|ay)\s+(.+)$/i);line=match?`${match[1]} = ${normalizeHumanExpression(match[2],map)}`:`# Check assignment: ${body}`}
    else if((keyword=startsKeyword(original,map.ask))){body=original.slice(keyword.length).trim();const match=body.match(/^([A-Za-z_]\w*)\s+(.+)$/);line=match?`${match[1]} = input(${match[2]})`:`input(${body})`}
    else if((keyword=startsKeyword(original,map.elif))){indent=Math.max(0,indent-1);body=original.slice(keyword.length);line=`elif ${normalizeHumanExpression(body,map)}:`;opens=true}
    else if((keyword=startsKeyword(original,map.if))){body=original.slice(keyword.length);line=`if ${normalizeHumanExpression(body,map)}:`;opens=true}
    else if((keyword=startsKeyword(original,map.repeat))){body=original.slice(keyword.length).trim();const count=body.match(/(.+?)\s+(?:times|beses)$/i)?.[1]||body;line=`for _ in range(${normalizeHumanExpression(count,map)}):`;opens=true}
    else if((keyword=startsKeyword(original,map.each))){body=original.slice(keyword.length).trim();const match=body.match(/^([A-Za-z_]\w*)\s+(?:in|sa)\s+(.+)$/i);line=match?`for ${match[1]} in ${normalizeHumanExpression(match[2],map)}:`:`# Check loop: ${body}`;opens=Boolean(match)}
    else if((keyword=startsKeyword(original,map.fn))){body=original.slice(keyword.length).trim();const match=body.match(/^([A-Za-z_]\w*)\s*(?:with|gamit)?\s*\(?([^)]*)\)?$/i);line=match?`def ${match[1]}(${match[2].replace(/\band\b|\bat\b/gi,",")}):`:`# Check function: ${body}`;opens=Boolean(match)}
    else if((keyword=startsKeyword(original,map.class))){body=original.slice(keyword.length).trim().replace(/\s+(?:extends|mana sa)\s+/i,"(");if(body.includes("(")&&!body.endsWith(")"))body+=")";line=`class ${body}:`;opens=true}
    else if((keyword=startsKeyword(original,map.ret))){line=`return ${normalizeHumanExpression(original.slice(keyword.length),map)}`}
    else line=normalizeHumanExpression(original,map);
    output.push("    ".repeat(indent)+line.trim());if(opens)indent++;
  }return output.join("\n");
}
function javaValue(value){return value.replace(/\bTrue\b/g,"true").replace(/\bFalse\b/g,"false").replace(/\bNone\b/g,"null").replace(/\band\b/g,"&&").replace(/\bor\b/g,"||").replace(/\bnot\s+/g,"!").replace(/\blen\((.*?)\)/g,"$1.size()").replace(/str\((.*?)\)/g,"String.valueOf($1)")}
function cppValue(value){return value.replace(/\bTrue\b/g,"true").replace(/\bFalse\b/g,"false").replace(/\bNone\b/g,"nullptr").replace(/\band\b/g,"&&").replace(/\bor\b/g,"||").replace(/\bnot\s+/g,"!").replace(/\blen\((.*?)\)/g,"$1.size()").replace(/str\((.*?)\)/g,"std::to_string($1)")}
async function transpileSource(source,input,target,customPrint){
  if(input === "yaml") { const project=parseProjectYAML(source); if(!project.components.length)throw new Error("No GUI components found."); return ({java:projectToSwing,cpp:projectToWin32,python:projectToPythonUI,swing:projectToSwing,tkinter:projectToTkinter,pyqt:projectToPyQt,kivy:projectToKivy}[target])(project); }
  if(!["java","cpp","python"].includes(target))throw new Error("Choose GUI YAML for GUI framework exports.");
  const python=input.startsWith("human-")?humanToPython(source,input,customPrint):String(source);
  return window.ReyDev.compilePython(python,target);
}

const TRANSPILE_SAMPLES={python:`class Engineer:\n    def __init__(self, name):\n        self.name = name\n\n    def introduce(self):\n        return "Hello, " + self.name\n\nrey = Engineer("Rey")\nprint("Portfolio OS")\nfor i in range(3):\n    print(i)`,"human-en":`class Engineer\n    function introduce with name\n        say "Hello, " + name\n        return name\n    end\nend\nset person to "Rey"\nsay "Welcome, " + person\nrepeat 3 times\n    say "Building locally"\nend`,"human-fil":`klase Engineer\n    gawain ipakilala gamit pangalan\n        ipakita "Kumusta, " + pangalan\n        ibalik pangalan\n    wakas\nwakas\nitakda tao bilang "Rey"\nipakita "Maligayang pagdating, " + tao\nulitin 3 beses\n    ipakita "Lokal na bumubuo"\nwakas`,yaml:`app: "Connected Calculator"\ncomponents:\n  - id: input1\n    type: input\n    text: "First number"\n    x: 60\n    y: 80\n    width: 180\n  - id: input2\n    type: input\n    text: "Second number"\n    x: 60\n    y: 140\n    width: 180\n  - id: calculate\n    type: button\n    text: "Add"\n    x: 300\n    y: 110\n    width: 120\n    operation: add\n  - id: result\n    type: output\n    text: "Result"\n    x: 500\n    y: 110\n    width: 160\nconnections:\n  - from: input1\n    to: calculate\n  - from: input2\n    to: calculate\n  - from: calculate\n    to: result`};
function initTranspiler(win){const input=$("[data-transpile-input]",win),target=$("[data-transpile-target]",win),source=$("[data-transpile-source]",win),output=$("[data-transpile-output]",win),custom=$("[data-custom-print]",win);let request=0;const run=async()=>{const id=++request;output.textContent="Compiling…";try{const result=await transpileSource(source.value,input.value,target.value,custom.value);if(id===request)output.textContent=result}catch(error){if(id===request)output.textContent="Compiler error: "+cleanText(error.message,500)}};$("[data-transpile-run]",win).addEventListener("click",run);$("[data-transpile-sample]",win).addEventListener("click",()=>{source.value=TRANSPILE_SAMPLES[input.value]||TRANSPILE_SAMPLES.python;run()});input.addEventListener("change",()=>{source.value=TRANSPILE_SAMPLES[input.value]||TRANSPILE_SAMPLES.python;if(input.value==="yaml"&&!['swing','tkinter','pyqt','kivy'].includes(target.value))target.value="swing";run()});target.addEventListener("change",run);$("[data-transpile-copy]",win).addEventListener("click",async()=>{try{await navigator.clipboard.writeText(output.textContent);toast("Copied","Generated source is on the clipboard.")}catch{toast("Copy unavailable","Select the output and copy it manually.")}});$("[data-transpile-download]",win).addEventListener("click",()=>{const ext={java:".java",cpp:".cpp",python:".py",swing:"-swing.java",tkinter:"-tkinter.py",pyqt:"-pyqt.py",kivy:"-kivy.py"}[target.value]||".txt";downloadText("portfolio-generated"+ext,output.textContent)});$("[data-install-transpiled]",win).addEventListener("click",()=>{const pkg={format:"portfolio-os-app/v1",name:"Transpiled Source",icon:"{ }",components:[{id:"title",type:"label",text:`${input.options[input.selectedIndex].text} → ${target.options[target.selectedIndex].text}`,x:35,y:28,w:600},{id:"source",type:"output",text:cleanText(output.textContent,1500),x:35,y:85,w:650}],connections:[],source:cleanText(output.textContent,12000),createdAt:new Date().toISOString()};installPackage(pkg);toast("Source installed","Open it from App Studio.")});run()}

const LOCAL_KNOWLEDGE=[
  {tags:"experience champ software engineer java spring angular enterprise cargo oauth oracle",text:"Rey is a Software Engineer at CHAMP Cargosystems. His work spans Angular, Java, Spring, APIs, OAuth, search, caching, Oracle, reusable components, and enterprise air-cargo systems."},
  {tags:"education mapua computer science artificial intelligence",text:"Rey earned a BS in Computer Science with a specialization in Artificial Intelligence from Mapúa University."},
  {tags:"skyler one record dangerous goods json ld cargo trust",text:"Skyler is a ONE Record trust engine that harmonizes dangerous-goods compliance and shipment-level JSON-LD for ground-handler checks."},
  {tags:"projects gesture cursor churn summarization computer vision machine learning nlp",text:"Rey’s selected work includes a deep-learning Gesture Cursor, rotational churn prediction with automated ML and cosine similarity, and extractive/abstractive text summarization using similarity graphs and PageRank."},
  {tags:"portfolio os gui designer bindings transpiler humancode themes pwa",text:"Portfolio OS is a local-first interactive portfolio with draggable windows, Windows/iOS/resume themes, a local terminal, IDE, GUI Designer with visual bindings, HumanCode transpilation, installable local apps, and PWA support."},
  {tags:"skills technologies java python cpp typescript angular spring ai ml nlp computer vision",text:"Core skills include Java, Spring, Angular, TypeScript, Python, C++, AI/ML, NLP, computer vision, Oracle, APIs, OAuth, and product-oriented UI engineering."}
];
function initAgent(win) {
  window.ReyDev.mountAssistant(win, LOCAL_KNOWLEDGE.map(item => item.text).join("\n"))
    .then(dispose => { if(win.classList.contains("closing")||!win.isConnected)dispose();else win._dispose=dispose; }).catch(error => {
      win.querySelector(".window-body").textContent = "Assistant could not start: " + error.message;
    });
}

const installedKey=()=>"portfolio-os:installed:"+slug(settings.profile);
function getInstalledApps(){const apps=storage.get(installedKey(),[]);return Array.isArray(apps)?apps.slice(0,24):[]}
function installPackage(raw){const normalized=validateProject(raw);if(!normalized.components.length)throw new Error("Package needs at least one component.");const serialized=JSON.stringify(raw);if(serialized.length>SECURITY.maxPackage)throw new Error("Package exceeds the 1 MB local limit.");const apps=getInstalledApps(),record={...normalized,format:"portfolio-os-app/v1",icon:cleanText(raw.icon||"◆",3),source:cleanText(raw.source||"",12000),installedAt:new Date().toISOString(),packageId:slug(raw.name)+"-"+Date.now()};const same=apps.findIndex(app=>slug(app.name)===slug(record.name));if(same>=0)apps.splice(same,1,record);else apps.unshift(record);if(!storage.set(installedKey(),apps.slice(0,24)))throw new Error("Local storage is full.");const store=openWindows.get("store");if(store&&typeof store._renderInstalled==="function")store._renderInstalled();return record}
function initStore(win){const root=$("[data-installed-apps]",win),input=$("#appFileInput");const render=()=>{root.replaceChildren();const apps=getInstalledApps();if(!apps.length){const empty=make("div","empty-card");empty.append(make("b",null,"No installed apps"),make("span",null,"Build one in GUI Designer or import a package."));root.append(empty);return}apps.forEach(app=>{const card=make("article"),icon=make("span","app-icon store-icon",app.icon||"◆"),copy=make("div"),open=make("button",null,"Open"),remove=make("button",null,"×");copy.append(make("b",null,app.name),make("small",null,`${app.components.length} components · local`));open.type="button";open.addEventListener("click",()=>openCustomAppWindow(app,"custom-"+app.packageId));remove.type="button";remove.title="Uninstall";remove.addEventListener("click",()=>{storage.set(installedKey(),getInstalledApps().filter(item=>item.packageId!==app.packageId));render();toast("App uninstalled",app.name)});card.append(icon,copy,open,remove);root.append(card)})};win._renderInstalled=render;$("[data-import-app]",win).addEventListener("click",()=>input.click());input.onchange=async()=>{const file=input.files?.[0];input.value="";if(!file)return;if(file.size>SECURITY.maxPackage){toast("Import blocked","Packages are limited to 1 MB.");return}if(file.name.toLowerCase().endsWith(".exe")){toast("EXE cannot run here","Import a Portfolio app package, or export source for a desktop compiler.");return}try{const text=await file.text();const raw=/\.ya?ml$/i.test(file.name)?parseProjectYAML(text):JSON.parse(text);installPackage(raw);render();toast("App installed",cleanText(raw.name||file.name,80))}catch(error){toast("Import failed",cleanText(error.message,180))}};render()}

async function requestInstall(){if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;toast("Install ready","Portfolio OS can now launch from your home screen.");return}toast("Install Portfolio OS","Use your browser menu and choose Add to Home Screen or Install app.")}
function initSettings(win){const name=$("[data-profile-name]",win),accent=$("[data-accent]",win),transparency=$("[data-transparency]",win),motion=$("[data-motion-toggle]",win);name.value=settings.profile;accent.value=settings.accent;transparency.value=settings.transparency;motion.checked=settings.motion;$$('[data-theme-choice]',win).forEach(button=>button.addEventListener("click",()=>{settings.theme=button.dataset.themeChoice;saveSettings();applySettings()}));accent.addEventListener("input",()=>{settings.accent=accent.value;saveSettings();applySettings()});transparency.addEventListener("input",()=>{settings.transparency=Number(transparency.value);saveSettings();applySettings()});motion.addEventListener("change",()=>{settings.motion=motion.checked;saveSettings();applySettings()});const changeProfile=()=>{const next=cleanText(name.value,40).trim();if(!next||next===settings.profile)return;saveSettings();const profiles=storage.get("portfolio-os:profiles",{active:settings.profile,entries:{}});profiles.active=next;storage.set("portfolio-os:profiles",profiles);loadSettings();name.value=settings.profile;accent.value=settings.accent;transparency.value=settings.transparency;motion.checked=settings.motion;toast("Profile switched",settings.profile)};name.addEventListener("change",changeProfile);name.addEventListener("keydown",event=>{if(event.key==="Enter"){event.preventDefault();changeProfile()}});$("[data-install-pwa]",win).addEventListener("click",requestInstall);$("[data-reset-settings]",win).addEventListener("click",()=>{settings=defaultSettings();saveSettings();applySettings();name.value=settings.profile;accent.value=settings.accent;transparency.value=settings.transparency;motion.checked=settings.motion;toast("Settings reset","The default Windows 11 theme is active.")})}
function wireSettingsNavigation(win){
  const cards=$$(".settings-cards article",win),themes=$(".theme-grid",win),heading=themes.previousElementSibling,search=$("aside input",win),buttons=$$("aside > button",win);
  const targets=[themes,$("[data-install-pwa]",win).closest("article"),$("[data-profile-name]",win).closest("article"),$("[data-motion-toggle]",win).closest("article"),cards[cards.length-1]];
  buttons.forEach((button,index)=>button.addEventListener("click",()=>{search.value="";filter();buttons.forEach(item=>item.classList.toggle("active",item===button));targets[index]?.scrollIntoView({block:"nearest",behavior:settings.motion?"smooth":"instant"});targets[index]?.querySelector("input,button")?.focus({preventScroll:true})}));
  function filter(){const query=search.value.trim().toLowerCase();cards.forEach(card=>card.hidden=!card.textContent.toLowerCase().includes(query));themes.hidden=heading.hidden=!!query&&!"theme windows ios resume".includes(query)}
  search.addEventListener("input",filter);
}
function initCalculator(win){const expression=$("[data-calc-expression]",win),output=$("[data-calc-output]",win);let value="";const show=()=>{expression.textContent=value;output.textContent=value||"0"};$$('[data-calc]',win).forEach(button=>button.addEventListener("click",()=>{const token=button.dataset.calc;if(token==="clear")value="";else if(token==="sign"){if(value&&/^-?\d+(?:\.\d+)?$/.test(value))value=String(-Number(value))}else if(token==="percent"){if(value&&/^-?\d+(?:\.\d+)?$/.test(value))value=String(Number(value)/100)}else if(token==="="){try{const result=safeArithmetic(value);expression.textContent=value+" =";value=String(result);output.textContent=value;return}catch{expression.textContent="Invalid expression";value="";output.textContent="0";return}}else if(value.length<80)value+=token;show()}));show()}

function finishBoot(){const boot=$("#bootScreen");if(boot.classList.contains("done"))return;boot.classList.add("done");setTimeout(()=>boot.setAttribute("aria-hidden","true"),700)}
function initDesktop(){
  loadSettings();updateClock();setInterval(updateClock,30000);const bootTimer=setTimeout(finishBoot,settings.motion?1750:120);$("#bootSkip").addEventListener("click",()=>{clearTimeout(bootTimer);finishBoot()});
  document.addEventListener("click",event=>{const launcher=event.target.closest("[data-open]");if(launcher){openApp(launcher.dataset.open);return}if(!event.target.closest(".panel-pop")&&!event.target.closest("#startButton")&&!event.target.closest("#trayButton")&&!event.target.closest("#taskSearch"))closePanels()});
  $("#startButton").addEventListener("click",event=>{event.stopPropagation();togglePanel("startMenu")});$("#taskSearch").addEventListener("click",event=>{event.stopPropagation();togglePanel("startMenu")});$("#trayButton").addEventListener("click",event=>{event.stopPropagation();togglePanel("quickPanel")});$("#startSearch").addEventListener("input",event=>{const query=event.target.value.trim().toLowerCase();$$('#startApps button').forEach(button=>button.hidden=!button.dataset.name.includes(query))});
  $("#desktop").addEventListener("contextmenu",event=>{if(event.target.closest(".app-window,.taskbar,.panel-pop"))return;event.preventDefault();closePanels();const menu=$("#contextMenu");menu.style.left=clamp(event.clientX,8,innerWidth-190)+"px";menu.style.top=clamp(event.clientY,8,innerHeight-150)+"px";menu.classList.add("open")});$("#refreshDesktop").addEventListener("click",()=>{const icons=$(".desktop-icons");icons.classList.remove("refreshed");requestAnimationFrame(()=>icons.classList.add("refreshed"));toast("Desktop refreshed","Everything is up to date.")});
  $("#lockButton").addEventListener("click",()=>{closePanels();const lock=$("#lockScreen");lock.classList.add("open");lock.setAttribute("aria-hidden","false")});$("#unlockButton").addEventListener("click",()=>{const lock=$("#lockScreen");lock.classList.remove("open");lock.setAttribute("aria-hidden","true")});
  $("#brightnessRange").addEventListener("input",event=>document.documentElement.style.setProperty("--brightness",String(Number(event.target.value)/100)));$("#focusToggle").addEventListener("click",event=>{event.currentTarget.classList.toggle("active");document.body.classList.toggle("focus-mode");toast("Focus mode",document.body.classList.contains("focus-mode")?"Ambient motion and desktop distractions reduced.":"Desktop restored.")});
  $("#installPwaTop").addEventListener("click",requestInstall);window.addEventListener("beforeinstallprompt",event=>{event.preventDefault();deferredInstall=event;$("#installPwaTop").hidden=false});window.addEventListener("appinstalled",()=>toast("Portfolio OS installed","Launch it like a native app."));
  if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));
  const wallpaper=$(".wallpaper");$("#desktop").addEventListener("pointermove",event=>{if(!settings.motion||innerWidth<=820||event.target.closest(".app-window,.panel-pop,.taskbar"))return;const x=(event.clientX/innerWidth-.5)*-7,y=(event.clientY/innerHeight-.5)*-7;wallpaper.style.transform=`scale(1.03) translate(${x}px,${y}px)`});
  document.addEventListener("keydown",event=>{if(event.key==="Escape"){closePanels();const focused=$(".app-window.focused");if(focused&&event.shiftKey)closeWindow(focused)}if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="k"){event.preventDefault();togglePanel("startMenu")}});
}
initDesktop();
