import Foundation
import Security
import ZIPFoundation

enum KeychainStore{private static let service="com.rvmendillo.ipabuilder.github",account="github-token";static func load()->String{let q:[String:Any]=[kSecClass as String:kSecClassGenericPassword,kSecAttrService as String:service,kSecAttrAccount as String:account,kSecReturnData as String:true,kSecMatchLimit as String:kSecMatchLimitOne];var item:CFTypeRef?;guard SecItemCopyMatching(q as CFDictionary,&item)==errSecSuccess,let d=item as? Data,let v=String(data:d,encoding:.utf8)else{return ""};return v};static func save(_ v:String)throws{delete();let q:[String:Any]=[kSecClass as String:kSecClassGenericPassword,kSecAttrService as String:service,kSecAttrAccount as String:account,kSecAttrAccessible as String:kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly,kSecValueData as String:Data(v.utf8)];let s=SecItemAdd(q as CFDictionary,nil);guard s==errSecSuccess else{throw NSError(domain:NSOSStatusErrorDomain,code:Int(s))}};static func delete(){SecItemDelete([kSecClass as String:kSecClassGenericPassword,kSecAttrService as String:service,kSecAttrAccount as String:account] as CFDictionary)}}
struct GitHubAPIError:LocalizedError{let message:String;var errorDescription:String?{message}}
private struct ContentUploadResponse:Decodable{struct ContentInfo:Decodable{let sha:String};struct CommitInfo:Decodable{let sha:String};let content:ContentInfo?;let commit:CommitInfo?}
private struct WorkflowRunEnvelope:Decodable{let workflow_runs:[WorkflowRun]};private struct WorkflowRun:Decodable{let id:Int64;let status:String;let conclusion:String?;let display_title:String;let html_url:String?;let head_sha:String};private struct ArtifactEnvelope:Decodable{let artifacts:[WorkflowArtifact]};private struct WorkflowArtifact:Decodable{let id:Int64;let name:String;let expired:Bool}

@MainActor final class GitHubBuildManager:ObservableObject{
 @Published var token:String;@Published var owner:String;@Published var repo:String;@Published var status="Ready";@Published var isBuilding=false;@Published var ipaURL:URL?;@Published var lastRunURL:URL?;@Published var lastError:String?;private let workflowFile="ipa-builder-service.yml",jobsBranch="ipa-builder-jobs"
 init(){token=KeychainStore.load();owner=UserDefaults.standard.string(forKey:"github.owner") ?? "rvmendillo";repo=UserDefaults.standard.string(forKey:"github.repo") ?? "portfolio"};var hasCredential:Bool{!token.trimmingCharacters(in:.whitespacesAndNewlines).isEmpty}
 func saveCredential(){do{let clean=token.trimmingCharacters(in:.whitespacesAndNewlines);guard !clean.isEmpty else{throw GitHubAPIError(message:"Enter a GitHub fine-grained token first.")};try KeychainStore.save(clean);token=clean;UserDefaults.standard.set(owner,forKey:"github.owner");UserDefaults.standard.set(repo,forKey:"github.repo");status="GitHub access saved in Keychain";lastError=nil}catch{lastError=error.localizedDescription}}
 func disconnect(){KeychainStore.delete();token="";ipaURL=nil;lastRunURL=nil;status="Disconnected"}
 func build(project:StudioProject)async{guard hasCredential else{lastError="Save a GitHub access token first.";return};isBuilding=true;ipaURL=nil;lastRunURL=nil;lastError=nil;let jobID=UUID().uuidString.lowercased(),jobPath="ipa-builder-jobs/\(jobID)/project.json";var uploadedSHA:String?;do{status="Uploading ReyForge project…";let e=JSONEncoder();e.outputFormatting=[.sortedKeys];e.dateEncodingStrategy=.iso8601;let data=try e.encode(project);let upload=try await uploadProject(data,path:jobPath,jobID:jobID);uploadedSHA=upload.contentSHA;status="macOS build queued…";let run=try await findRun(commitSHA:upload.commitSHA);if let u=run.html_url{lastRunURL=URL(string:u)};let completed=try await wait(runID:run.id);guard completed.conclusion=="success" else{throw GitHubAPIError(message:"GitHub build finished with: \(completed.conclusion ?? "unknown")")};status="Downloading generated IPA…";let artifact=try await findArtifact(runID:run.id,jobID:jobID);let zip=try await request(path:"/repos/\(owner)/\(repo)/actions/artifacts/\(artifact.id)/zip").0;status="Extracting IPA…";ipaURL=try extractIPA(zipData:zip,projectName:project.name,jobID:jobID);status=project.widget.enabled ? "App + Widget IPA ready":"IPA ready"}catch{lastError=error.localizedDescription;status="Build failed"};if let uploadedSHA{try? await deleteProject(path:jobPath,sha:uploadedSHA,jobID:jobID)};isBuilding=false}
 private func apiURL(path:String,query:[URLQueryItem]=[])throws->URL{var c=URLComponents();c.scheme="https";c.host="api.github.com";c.path=path;if !query.isEmpty{c.queryItems=query};guard let u=c.url else{throw GitHubAPIError(message:"Invalid GitHub API URL.")};return u}
 private func request(path:String,method:String="GET",query:[URLQueryItem]=[],jsonBody:Any?=nil)async throws->(Data,HTTPURLResponse){var r=URLRequest(url:try apiURL(path:path,query:query));r.httpMethod=method;r.setValue("Bearer \(token)",forHTTPHeaderField:"Authorization");r.setValue("application/vnd.github+json",forHTTPHeaderField:"Accept");r.setValue("2022-11-28",forHTTPHeaderField:"X-GitHub-Api-Version");if let jsonBody{r.httpBody=try JSONSerialization.data(withJSONObject:jsonBody);r.setValue("application/json",forHTTPHeaderField:"Content-Type")};let(data,response)=try await URLSession.shared.data(for:r);guard let h=response as? HTTPURLResponse else{throw GitHubAPIError(message:"Invalid GitHub response.")};guard(200...299).contains(h.statusCode)else{let body=String(data:data,encoding:.utf8) ?? "";throw GitHubAPIError(message:"GitHub API \(h.statusCode): \(body.isEmpty ? "request failed":body)")};return(data,h)}
 private func uploadProject(_ data:Data,path:String,jobID:String)async throws->(contentSHA:String,commitSHA:String){let body:[String:Any]=["message":"ReyForge build \(jobID)","content":data.base64EncodedString(),"branch":jobsBranch];let(d,_)=try await request(path:"/repos/\(owner)/\(repo)/contents/\(path)",method:"PUT",jsonBody:body);let x=try JSONDecoder().decode(ContentUploadResponse.self,from:d);guard let cs=x.content?.sha,let commit=x.commit?.sha else{throw GitHubAPIError(message:"Project upload did not return commit metadata.")};return(cs,commit)}
 private func findRun(commitSHA:String)async throws->WorkflowRun{for _ in 0..<80{let(d,_)=try await request(path:"/repos/\(owner)/\(repo)/actions/workflows/\(workflowFile)/runs",query:[URLQueryItem(name:"event",value:"push"),URLQueryItem(name:"branch",value:jobsBranch),URLQueryItem(name:"per_page",value:"30")]);let e=try JSONDecoder().decode(WorkflowRunEnvelope.self,from:d);if let r=e.workflow_runs.first(where:{$0.head_sha==commitSHA}){return r};try await Task.sleep(nanoseconds:3_000_000_000)};throw GitHubAPIError(message:"The ReyForge macOS build did not appear in GitHub Actions.")}
 private func wait(runID:Int64)async throws->WorkflowRun{for _ in 0..<180{let(d,_)=try await request(path:"/repos/\(owner)/\(repo)/actions/runs/\(runID)");let r=try JSONDecoder().decode(WorkflowRun.self,from:d);status=r.status=="queued" ? "macOS runner queued…":"macOS runner: \(r.status)…";if r.status=="completed"{return r};try await Task.sleep(nanoseconds:4_000_000_000)};throw GitHubAPIError(message:"Build monitoring timed out.")}
 private func findArtifact(runID:Int64,jobID:String)async throws->WorkflowArtifact{let(d,_)=try await request(path:"/repos/\(owner)/\(repo)/actions/runs/\(runID)/artifacts");let e=try JSONDecoder().decode(ArtifactEnvelope.self,from:d);guard let a=e.artifacts.first(where:{$0.name=="ipa-\(jobID)" && !$0.expired})else{throw GitHubAPIError(message:"The completed build did not expose its IPA artifact.")};return a}
 private func deleteProject(path:String,sha:String,jobID:String)async throws{_ = try await request(path:"/repos/\(owner)/\(repo)/contents/\(path)",method:"DELETE",jsonBody:["message":"[skip ci] Clean ReyForge job \(jobID)","sha":sha,"branch":jobsBranch])}
 private func extractIPA(zipData:Data,projectName:String,jobID:String)throws->URL{let fm=FileManager.default,zip=fm.temporaryDirectory.appendingPathComponent("reyforge-\(jobID).zip");try zipData.write(to:zip,options:.atomic);let a=try Archive(url:zip,accessMode:.read);guard let e=a.first(where:{$0.type == .file && $0.path.lowercased().hasSuffix(".ipa")})else{throw GitHubAPIError(message:"Downloaded artifact did not contain an IPA.")};let builds=fm.urls(for:.documentDirectory,in:.userDomainMask)[0].appendingPathComponent("Builds",isDirectory:true);try fm.createDirectory(at:builds,withIntermediateDirectories:true);let safe=projectName.replacingOccurrences(of:"/",with:"-").replacingOccurrences(of:":",with:"-");let dest=builds.appendingPathComponent("\(safe)-\(jobID.prefix(8)).ipa");if fm.fileExists(atPath:dest.path){try fm.removeItem(at:dest)};try a.extract(e,to:dest);try? fm.removeItem(at:zip);return dest}
}
